### ISSUE TITLE
Latest OS for mid-2011 MacBook Air

### ISSUE THREAD

**Issue by scripting** [scripting/Scripting-News#112]
I have a mid-2011 MacBook Air that I want to update to the latest OS that will run on it. I asked for help [on Facebook](https://www.facebook.com/photo.php?fbid=913978282142911&set=a.113966572144090&type=3&theater), but none of the suggestions work. So let's start over.

![image](https://user-images.githubusercontent.com/1686843/54824623-dc2dec00-4c81-11e9-92b8-f7c0eb1e8fe9.png)

![image](https://user-images.githubusercontent.com/1686843/54824492-7b9eaf00-4c81-11e9-8a61-f474be1bdbb4.png)

I understand it can run 10.13. But I have yet to find a download that will install 10.13. 

And there was a change in the dmg format somewhere along the line, so that might also be an issue.

**Comment by rosskarchner** [comment]
I looked at the Facebook thread, and didn't see any mention of downloading it from the Mac App Store. Does this link do anything for you? https://itunes.apple.com/us/app/macos-high-sierra/id1246284741?ls=1&mt=12

**Comment by scripting** [comment]
@rosskarchner -- we definitely tried the Mac App Store, but your link works, but didn't yield a download. Here's the error message.

![image](https://user-images.githubusercontent.com/1686843/54825011-e2709800-4c82-11e9-91e5-b823895e4061.png)

**Comment by roenass** [comment]
I believe Mojave will not run on it, but more importantly, Software Update/App Store should include the latest applicable OS version (and maybe the inapplicable ones as well).  High Sierra should be available.

Doesn't it?  Then the issue is probably that you're still running Lion (10.7) and the installers are requiring Mountain Lion at least.  Can you find Mountain Lion in the App Store and update to that first?

**Comment by scripting** [comment]
We're now repeating what we did in the Facebook thread. Searching for the OS versions by name in the Mac App Store does not get you the OS, it gets you things that mention it in their description or title.

**Comment by rosskarchner** [comment]
It seems like the world opens up if you can just get 10.8, according to this page, you can get a download code for $20 https://www.apple.com/shop/product/D6377Z/A/os-x-mountain-lion

But I also see elsewhere that Mountain Lion isn't on the mac app store anymore, so I'm not 100% sure it'll work. But then, you'll at least have a customer service issue with Apple? Yay?

**Comment by mcenirm** [comment]
If you already have a different Mac running at least 10.8, then you might be able to use the High Sierra direct app store link to download the full installer. Then you can create [USB installation media](https://support.apple.com/en-us/HT201372). I think the current USB media size needed is 12 GB.

Any Mac running an OS before 10.8 can't upgrade, because of the app store problems that you encountered. Instead you need to have a full installer on external media. Unfortunately, there is no way to download a full installer (legitimately from Apple), without using the app store on 10.8 or later.

**Comment by mcenirm** [comment]
[How to upgrade to OS X El Capitan](https://support.apple.com/en-us/HT206886) (10.11) suggests there might be an option:

> If you're using Leopard, [upgrade to Snow Leopard](http://store.apple.com/us/product/MC573/mac-os-x-106-snow-leopard) to get the App Store. Then check for software updates by choosing Software Update from the Apple menu. After installing all Snow Leopard updates, you should have the App Store app and can use it to [download OS X El Capitan](https://support.apple.com/en-us/HT206886#download). You can then use El Capitan to upgrade to a later macOS.

Since 10.7 (Lion) is later than 10.6 (Snow Leopard), maybe those instructions apply to your situation. Make sure all the updates are installed, then try the [direct link for 10.11](https://itunes.apple.com/app/os-x-el-capitan/id1147835434?ls=1&mt=12).

**Comment by scripting** [comment]
@mcenirm -- yes I have a machine running 10.13.6 here, and at another location a couple of fully updated Mojave machines.

**Comment by scripting** [comment]
@mcenirm -- I am downloading El Capitan now. 37 minutes. That's encouraging because previous downloads were much smaller. Will keep you posted.

**Comment by scripting** [comment]
It's installing El Capitan. Looks quite promising. :boom:

**Comment by dsearls** [comment]
That model (MacBookAir4,2) can supposedly run the latest OS (Mojave) with a patch that's here: http://dosdude1.com/mojave/ There are cautions listed. Otherwise High Sierra is the limit. We have one of those here, and upgraded it to High Sierra. Works fine.

**Comment by scripting** [comment]
Bingo!

![image](https://user-images.githubusercontent.com/1686843/54837842-bca4bc80-4c9d-11e9-8d2c-3f42f1f9a4bd.png)

Thanks @mcenirm -- you win the prize in this thread.

There's more to do. @dsearls for now I'm happy where I am. It means the screen isn't this anachronistic jarring thing. It's just a hobby thing. Kind of like getting an old Mac 512K to run Frontier (which of course it can't).

**Comment by scripting** [comment]
I'm now installing High Sierra.

**Comment by zahidhanif** [comment]
I have Mac Mini (Mid 2011) and went through a similar process. Make sure your create a time machine backup as I have had to re-install recently and had to spend a couple of hours getting back to High Sierra.

**Comment by timguy99** [comment]
Interesting. I have a Mac Mini (although might be too old) that I thought couldn't be upgraded. Always just figured the App Store would provide the right upgrade path. I may have to try this method.

**Comment by scripting** [comment]
![image](https://user-images.githubusercontent.com/1686843/54847063-c0dbd480-4cb3-11e9-9018-7d6372953b3a.png)

**Comment by ChristopherA** [comment]
I have a mid 2011 MacBook Air running High Sierra with no problem. It does not upgrade to Mojave. Booted it off of an external usb drive to install OS.

**Comment by scripting** [comment]
@ChristopherA -- see the message before yours in the thread. We got there. ;-)

I'm closing this issue.
