### ISSUE TITLE
Nightly email looks crappy on iPhone

### ISSUE THREAD

**Issue by scripting** [scripting/Scripting-News#146]
I got a couple of reports from people who use the Mail app on iPhones to read the nightly email, and am able to reproduce the problem here. The contents of the mail only fills a portion of the window horizontally. Not a good look. Apparently previously it filled the space. I've started a thread to gather info about this. I don't know how to debug this, but I will try. 

![image](https://user-images.githubusercontent.com/1686843/73074870-98e76f80-3e88-11ea-8d14-58c8bab9af3b.png)

**Comment by scripting** [comment]
Any ideas on how to experiment with HTML in the iPhone email client? Obviously it's not liking something about the CSS? Not sure where to begin.

**Comment by cshotton** [comment]
I went back and tried to recreate this and to also see whether the problem was present in earlier messages. Unfortunately, when viewing the message a second time, the formatting was correct and flowed to the full screen width. It also was fine for earlier messages.

I thought it could be related to "Dark Mode", so I switched back to that UI setting, and then restarted Mail. However, the formatting remained the same and looked OK.

This seems to be a problem with opening the message for the first time. Perhaps you could confirm by resending new messages with the content and see if first opens are borked and subsequent ones are OK. If that's the case, this is either a timing issue with styles not being loaded (are they in-line or in a remote stylesheet) in time for the first rendering, or a bug in the HTML renderer in Mail.

**Comment by scripting** [comment]
Okay I did what you did and got different, confusing, results. 

1. I re-opened the message with the bad formatting, and the second time it had the bad formatting as before. 

2. I opened the email from the 22nd, expecting it to look shitty, but it looked fine, which seems to indicate that something about the formatting changed between the two emails. 

3. But I swear I changed nothing having to do with the emails. 

Here's my suggestion. Let's re-visit this tomorrow and see if it happens again. I'm guessing the problem has to do with the content of yesterday's posts, not with any of the automated formatting. 

I included an iframe with a C-SPAN video yesterday. It caused (different) problems in GMail. It was a risky move that I won't try again.

**Comment by scripting** [comment]
My current theory is that the problem was caused by an &lt;iframe> in yesterday's email. Let's see what tonight's email looks like.

**Comment by scripting** [comment]
I believe the &lt;iframe> theory was correct because last night's email looks perfect in the mail app on my iPhone. Closing this for now.

**Comment by scripting** [comment]
![IMG_5CC2D2C6BC76-1](https://user-images.githubusercontent.com/1686843/73125631-f35ef980-3f76-11ea-8f6e-2d00af5c7f03.jpeg)

**Comment by scripting** [comment]
![IMG_7F92308AD690-1](https://user-images.githubusercontent.com/1686843/73125651-3de07600-3f77-11ea-90ba-62a51c3e0686.jpeg)

**Comment by scripting** [comment]
![IMG_7F92308AD690-1](https://user-images.githubusercontent.com/1686843/73125661-5b154480-3f77-11ea-843f-544ab7d2b73d.jpeg)
