### ISSUE TITLE
Drummer for poets?

### ISSUE THREAD

**Issue by scripting** [scripting/Scripting-News#216]
A place to ask questions about this piece. 

http://scripting.com/2021/07/09/142855.html?title=drummerForPoets

**Comment by scripting** [comment]
PS: For programmers, the key piece of software has a very funny name. <a href="https://github.com/scripting/appServer">daveappserver</a>. It's an application server, perfectly set up to host Drummer, because in fact it is what I use to host Drummer. :smile:

**Comment by andysylvester** [comment]
I think if a product is server-based, the easier it is to install, the better. "Zero-install" would be the ideal case....

It looks like Digital Ocean's snapshot offering (https://docs.digitalocean.com/products/images/snapshots/) might be the best fit on their platform. From my experience with the PagePark Glitch demo, that could certainly be another solution. 

Looking at daveappserver, I see that it requires having a Twitter app key and secret, which means that the user needs a Twitter developer account and has to have generated that key/secret. I added a walkthrough of this process to my latest book. Without that kind of writeup/example, I think many users that might want to try it out would not be motivated to go through the effort.

**Comment by scripting** [comment]
@andysylvester -- I almost added a bit to that piece about identity being the obstacle to success.

At some point someone is going to have to do a fully open source, easy to operate identity service that you can operate yourself. I have half of it with the newsletter subscription software. I just don't have the ability to focus on it until Drummer is ready for prime time.

Have you tried creating a new app on Twitter recently? If so, are you able to do it?

**Comment by andysylvester** [comment]
The last time I created an app using V1.1 Twitter API was December 2020. I went ahead and created a new app today, was able to generate keys, and also created a "project" (which supposedly allows access to some V2.0 API stuff). It looks like I can create a maximum of 10 V1.1 API apps.

**Comment by scripting** [comment]
@andysylvester -- I'm glad to hear you can still create apps. 

I'm going to go ahead and write a howto for setting up a Drummer server based on that.

**Comment by fmcpherson** [comment]
If you haven’t heard of it, I’ve found that Cloudron at https://www.cloudron.io/ provides a pretty easy way to set up a server to host an application. I don’t have any experience with it as a developer so not sure how the packaging / distribution works. Netlify was pretty easy too.

**Comment by fmcpherson** [comment]
I got an email from Digital Ocean today about their App Platform: https://www.digitalocean.com/products/app-platform/. Minimum cost is $5 per month, for that you can run an app in 512 mb of RAM with 1vCPU. 

Decided to try deploying pagePark to it. I did not read any doco and found it pretty straight forward with some caveats.

It builds from a Github repo but needs access to an account, thus I forked the scripting\pagePark repo to my Github account. From this point once authorized I had one hiccup with the deploy process, it needs package-lock.json in the repo. I had one from a local install I have of pagePark so I uploaded it to my repo. After this the build was success. 

Digital Ocean creates a URL for the app, the one it generated for this deployment is https://page-park-odl72.ondigitalocean.app/. A bonus, they appear to handle HTTPS access as well. Looks like I can use one of my own domains/subdomains, which I will try to configure next. The above may go away as I likely will destroy and re-build after making changes to the repo I describe below.

Console access is very limited... no sudo access, no access to apt. Looks like their service is intended to be entirely driven from Github, so probably want a config.json in the root folder of the repo and create a domains folder so that you can check-in files to have them deployed to the right folder. For my test accessed the console, cd domains and echo "Hello world! This is an instance of pagePark hosted in Digital Oceans apps.">index.md to have the page generated. 

I think the build process actually creates a docker container of page park and it appears to automatically map port 80 to 1339. I made no changes to config.json, so pagePark is running on 1339 but as you can tell, port 80 is working. 

More later, with more doco.

**Comment by fmcpherson** [comment]
I've finished deployment to my own subdomain: https://pagepark.frankmcpherson.net

I find it pretty easy but I have experience with this stuff so I am not a good judge. Deployment requires a repo in either Github or Gitlab or you have to provide your own docker image via docker hub. 

I current have one problem in that OPML files are not rendering, whether they are stored locally or mirrored.

**Comment by scripting** [comment]
Frank that isn't so much a problem with PagePark as the template used to render OPML files. It's something the user has control over, so if you wanted to fix it, you could -- just as easily as I could. 

Also I suspect this is the problem I'm having on the experimental Glitch site I set up.

http://pagepark.glitch.me/
